service:
  name: 'serverlesschallenge'

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    wabpackconfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
    createTodo:
      handler: src/functions/createTodo.handle
      events:
        - http:
            path: /todos/{userid}
            method: POST
            cors: true
      iamRolestatements:
        - Effect: Allow
          Action:
            - dynamo:Query
            - dynamo:PutItem
          Resource: 'arn:aws:dynamodb:${self.provider.region}:*:table/todos'
    getTodoByUserId:
      handler: src/functions/getTodoByUserId.handle
      events:
        - http:
            path: /todos/{userid}
            method: GET
            cors: true
      iamRolestatements:
        - Effect: Allow
          Action:
            - dynamo:Query
          Resource: 'arn:aws:dynamodb:${self.provider.region}:*:table/todos'

resources:
  Resources:
    dbTodos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos  
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH